### DISCUSSION TITLE
QGIS container of qfield cloud docker setup is keeps crashing in production deployment

### DISCUSSION THREAD

**Discussion by amitabhajana** [opengisch/QField#3671] [Q&A]
Hi,

I am first time trying to setup dockerized qfieldcloud on my production server by using this repo https://github.com/opengisch/qfieldcloud.git. but whenever i am trying to run the docker-compose.yml file by docker-compose up command, i can see the qgis container is keep crashing at the startup by showing error 
```
qfield_qgis                    | QGIS built
qfield_qgis exited with code 0
```

this is the service written in docker-compose.yml file
```
qgis:
    build:
      context: ./docker-qgis
    tty: true
    container_name: qfield_qgis
    command: bash -c "echo QGIS built"
    logging: *default-logging
```
Can anyone pls help me on this
